version: "3"

services:
  ansible:
    image: ansible/centos:remote-runner
    hostname: ansible
    domainname: docker.local
    volumes:
      - "./example/extra_vars:/extra_vars"
      - "./example/hosts:/etc/ansible/hosts"
      - "${VAULT_KEY}:/run/secrets/vault:ro"
      - ${PROJECT_HOME}:${PLAYBOOK_HOME}

  managed:
    image: ansible/centos:remote-target
    hostname: managed
    domainname: docker.local
    privileged: true
    networks:
      default:
        aliases:
          - managed
          - managed.docker.local
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
